# Stable v0.1 — 2025-10-19
# Kori Monorepo — GitHub Actions CI
# - Node 20.x LTS
# - pnpm 9 via Corepack (cache enabled)
# - Steps: install → typecheck → build → test → upload artifacts

name: CI

on:
  push:
    branches: ["main", "*/*", "*"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Enable Corepack & pnpm 9
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm -v

      - name: Install dependencies (workspace)
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm -r typecheck

      - name: Build
        run: pnpm -r build

      - name: Test
        run: pnpm -r test

      - name: Upload web dist
        if: ${{ always() && hashFiles('apps/web/dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist

      - name: Upload api dist
        if: ${{ always() && hashFiles('apps/api/dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: api-dist
          path: apps/api/dist
