# Stable v0.4 — 2025-10-19
# CI/CD Pipeline for Kori (Monorepo)
# Changelog v0.4:
# - Install pnpm via npm (robust) instead of relying on action/Corepack
# - Keep setup-node cache: pnpm for dependency caching

name: CI

on:
  push:
    branches:
      - main
      - "**/*"
      - "*"
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20.x (+ pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      # Robust install: ensure pnpm is on PATH
      - name: Install pnpm 9 (global)
        run: |
          npm i -g pnpm@9
          pnpm -v

      - name: Show tool versions
        run: |
          node -v
          pnpm -v

      - name: Install dependencies (workspace)
        run: pnpm install --frozen-lockfile

      - name: Prepare API env (non-secret)
        run: |
          if [ -f apps/api/.env.example ]; then cp apps/api/.env.example apps/api/.env; fi

      - name: Typecheck
        run: pnpm -r typecheck

      - name: Build
        run: pnpm -r build

      - name: Test
        run: pnpm -r test --if-present

      - name: Upload web dist
        if: ${{ always() && hashFiles('apps/web/dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist
          if-no-files-found: ignore

      - name: Upload api dist
        if: ${{ always() && hashFiles('apps/api/dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: api-dist
          path: |
            apps/api/dist
            apps/api/prisma/**
          if-no-files-found: ignore
