# Stable v0.5 — 2025-10-19
# CI/CD Pipeline for Kori (Monorepo)
# Changelog v0.5:
# - Avoid PATH issues: run pnpm via npx (PNPM="npx -y pnpm@9") in all steps

name: CI

on:
  push:
    branches:
      - main
      - "**/*"
      - "*"
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      PNPM: npx -y pnpm@9

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20.x (+ cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Show tool versions
        shell: bash
        run: |
          node -v
          $PNPM -v

      - name: Install dependencies (workspace)
        shell: bash
        run: $PNPM install --frozen-lockfile

      - name: Prepare API env (non-secret)
        shell: bash
        run: |
          if [ -f apps/api/.env.example ]; then cp apps/api/.env.example apps/api/.env; fi

      - name: Typecheck
        shell: bash
        run: $PNPM -r typecheck

      - name: Build
        shell: bash
        run: $PNPM -r build

      - name: Test
        shell: bash
        run: $PNPM -r test --if-present

      - name: Upload web dist
        if: ${{ always() && hashFiles('apps/web/dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist
          if-no-files-found: ignore

      - name: Upload api dist
        if: ${{ always() && hashFiles('apps/api/dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: api-dist
          path: |
            apps/api/dist
            apps/api/prisma/**
          if-no-files-found: ignore
